name: kuismobprog_535220142
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/share.png
    - img/basket.png
    - img/search.png
    - img/profile.png
    - img/add-1.jpg
    - img/add-2.jpg
    - img/add-3.jpg
    - img/gambarbawah.jpg
    - img/alfa1.jpg
    - img/alfa2.jpg
    - img/alfa3.jpg
    - img/alfa4.jpg
